---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoders-webapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ecoders-webapi
  template:
    metadata:
      labels:
        name: ecoders-webapi
    spec:
      containers:
      - name: webapi
        image: webservice
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080