apiVersion: v1
kind: Service
metadata:
  name: ecoders-web-service
spec:
  type: LoadBalancer
  selector:
    app: ecoders-webapi-30
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080