apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoders-webapi
  labels:
    app: ecoders-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecoders-webapi
  template:
    metadata:
      labels:
        app: ecoders-webapi
    spec:
      containers:
      - name: ecoders-webapi
        image: astronik/webservice
        imagePullPolicy: Always
        ports:
          - containerPort: 8080