apiVersion: v1
kind: Service
metadata:
  name: ecoders-web-service
spec:
  type: ClusterIP
  selector:
    app: ecoders-webapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
