apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
#    cert-manager.io/issuer: "letsencrypt-prod"
  name: ecoders-web-ingress
spec:
 # tls:
 #   - hosts:
 #       - ecoders.ca
 #    secretName: ecoders-web-tls
  rules:
    - host: ecoders.ca
      http:
        paths:
          - path: /
            backend:
              serviceName: ecoders-web-service
              servicePort: 80