apiVersion: v1
kind: Service
metadata:
  name: ecoders-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: ecoders-webapi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ecoders-web-service
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: ecoders.ca
      http:
        paths:
          - path: /
            backend:
              serviceName: ecoders-web-service
              servicePort: http